### ISSUE TITLE
Request example

### ISSUE THREAD

**Issue by kapes232** [Dirkster99/AvalonEdit-Samples#1]
Hi, before all thank you for share your great work.

Is possible to use your theme library in a simpler way, that is, an example not using MVVM?

My target is to apply a dark theme to AvalonEdit in C# highlight at the startup of my WPF project with simple code.

Best regards.

**Comment by Dirkster99** [comment]
You can just use the given theming sample and strip away all other themes just leaving dark at start-up time without a choice for selecting any other theme should get you to a more simplified version ...
